const images = {
  1: require('../assets/images/01-s.png'),
  2: require('../assets/images/02-s.png'),
  3: require('../assets/images/03-s.png'),
  4: require('../assets/images/04-s.png'),
  5: require('../assets/images/05-s.png'),
  6: require('../assets/images/06-s.png'),
  7: require('../assets/images/07-s.png'),
  8: require('../assets/images/08-s.png'),
  11: require('../assets/images/11-s.png'),
  12: require('../assets/images/12-s.png'),
  13: require('../assets/images/13-s.png'),
  14: require('../assets/images/14-s.png'),
  15: require('../assets/images/15-s.png'),
  16: require('../assets/images/16-s.png'),
  17: require('../assets/images/17-s.png'),
  18: require('../assets/images/18-s.png'),
  19: require('../assets/images/19-s.png'),
  20: require('../assets/images/20-s.png'),
  21: require('../assets/images/21-s.png'),
  22: require('../assets/images/22-s.png'),
  23: require('../assets/images/23-s.png'),
  24: require('../assets/images/24-s.png'),
  25: require('../assets/images/25-s.png'),
  26: require('../assets/images/26-s.png'),
  29: require('../assets/images/29-s.png'),
  30: require('../assets/images/30-s.png'),
  31: require('../assets/images/31-s.png'),
  32: require('../assets/images/32-s.png'),
  33: require('../assets/images/33-s.png'),
  34: require('../assets/images/34-s.png'),
  35: require('../assets/images/35-s.png'),
  36: require('../assets/images/36-s.png'),
  37: require('../assets/images/37-s.png'),
  38: require('../assets/images/38-s.png'),
  39: require('../assets/images/39-s.png'),
  40: require('../assets/images/40-s.png'),
  41: require('../assets/images/41-s.png'),
  42: require('../assets/images/42-s.png'),
  43: require('../assets/images/43-s.png'),
  44: require('../assets/images/44-s.png'),
};

export default images;
