export const SET_LOCATIONS = 'SET_LOCATIONS'
export const UPDATE_FAVORITES = 'UPDATE_FAVORITES'
export const DELETE_FAVORITE_LOCATION = 'DELETE_FAVORITE_LOCATION'
export const CHANGE_TEMPERATURE_UNITS = 'CHANGE_TEMPERATURE_UNITS'